-- CreateTable
CREATE TABLE "owner" (
    "OWNN_ID" TEXT NOT NULL,
    "OWNN_LNAME" TEXT NOT NULL,
    "OWNN_FNAME" TEXT NOT NULL,
    "OWNN_TEL" TEXT NOT NULL,
    "OWNN_MAIL" TEXT NOT NULL,
    "OWNN_MDP" TEXT NOT NULL,

    CONSTRAINT "owner_pkey" PRIMARY KEY ("OWNN_ID")
);

-- CreateTable
CREATE TABLE "tenant" (
    "TENN_ID" TEXT NOT NULL,
    "TENN_LNAME" TEXT NOT NULL,
    "TENN_FNAME" TEXT NOT NULL,
    "TENN_TEL" TEXT NOT NULL,
    "TENN_MAIL" TEXT NOT NULL,
    "TENN_MDP" TEXT NOT NULL,

    CONSTRAINT "tenant_pkey" PRIMARY KEY ("TENN_ID")
);
