-- CreateTable
CREATE TABLE "owner" (
    "OWNN_ID" SERIAL NOT NULL,
    "OWNC_LNAME" TEXT NOT NULL,
    "OWNC_FNAME" TEXT NOT NULL,
    "OWNN_TEL" INTEGER NOT NULL,
    "OWNC_MAIL" TEXT NOT NULL,
    "OWNC_MDP" TEXT NOT NULL,

    CONSTRAINT "owner_pkey" PRIMARY KEY ("OWNN_ID")
);

-- CreateTable
CREATE TABLE "tenant" (
    "TENN_ID" SERIAL NOT NULL,
    "TENC_LNAME" TEXT NOT NULL,
    "TENC_FNAME" TEXT NOT NULL,
    "TENN_TEL" INTEGER NOT NULL,
    "TENC_MAIL" TEXT NOT NULL,
    "TENC_MDP" TEXT NOT NULL,

    CONSTRAINT "tenant_pkey" PRIMARY KEY ("TENN_ID")
);
